name: Build Windows and Android Apps

on:
  push:
  workflow_dispatch:

jobs:

  # -------------------------
  # Windows Desktop App
  # -------------------------
  build-windows:
    name: Build Windows App
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build MSI
        run: ./gradlew :composeApp:packageMsi

      - name: Upload Windows Installer
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Installer
          path: composeApp/build/compose/binaries/main/msi/


  # -------------------------
  # Android App
  # -------------------------
  build-android:
    name: Build Android App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v4

      - name: Build Android APK
        run: ./gradlew :composeApp:assembleDebug

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: composeApp/build/outputs/apk/debug/*.apk